version: '2.22.0'

services:
  samba-server:
    build:
      context: ./samba-server
    ports:
      - "139:139"
      - "445:445"
      - "5000:5000"
    container_name: samba-server
  
  samba-client-1:
    build:
      context: ./samba-client
    ports:
      - "5001:5000"
    depends_on:
      - samba-server
    container_name: samba-client
      
networks:
  default:
    driver: bridge
